name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - uses: actions/checkout@v4
   - uses: xu-cheng/texlive-action@v2
     with:
       scheme: full
       run: |
         make4ht -c config.cfg -ua debug -d out ./IA_M/groups.tex "mathjax,fn-in"
   - name: Publish the web pages 
     uses:  peaceiris/actions-gh-pages@v3 
     with: 
       github_token: ${{ secrets.GITHUB_TOKEN }} 
       publish_dir: ./out
